# Generated by Django 4.2 on 2023-06-19 05:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='programminglanguage',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
