# Generated by Django 4.2 on 2023-06-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_programminglanguage_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='programminglanguage',
            managers=[
            ],
        ),
    ]
