# Generated by Django 4.2 on 2023-06-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_programminglanguage_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='programminglanguage',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='programminglanguage',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
