# Generated by Django 4.2 on 2023-06-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
