# Generated by Django 4.2 on 2023-06-19 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_programminglanguage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='SampleTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input', models.TextField(verbose_name='input data')),
                ('output', models.TextField(verbose_name='output data')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_test_cases', to='problems.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'Sample test case',
                'verbose_name_plural': 'Sample test cases',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_code', models.TextField(verbose_name='source code')),
                ('uuid', models.UUIDField(default=uuid.UUID('d286dc30-06d7-4053-a4bd-597c8359f876'), editable=False, verbose_name='uuid')),
                ('verdict', models.CharField(choices=[('waiting', 'Waiting'), ('compiling', 'Compiling'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong answer'), ('time_limit_exceeded', 'Time limit exceeded'), ('presentation_error', 'Presentation error'), ('compilation_error', 'Compilation error'), ('memory_limit_exceeded', 'Memory limit exceeded'), ('runtime_error', 'Runtime error')], default='waiting', max_length=32, verbose_name='verdict')),
                ('time', models.PositiveIntegerField(default=0, verbose_name='time')),
                ('memory', models.PositiveIntegerField(default=0, verbose_name='memory')),
                ('error', models.TextField(blank=True, null=True, verbose_name='error')),
                ('is_checked', models.BooleanField(default=False, verbose_name='is checked')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='common.programminglanguage', verbose_name='language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='problems.problem', verbose_name='problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input', models.TextField(verbose_name='input data')),
                ('output', models.TextField(verbose_name='output data')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'Test case',
                'verbose_name_plural': 'Test cases',
                'ordering': ['order'],
                'unique_together': {('problem', 'order')},
            },
        ),
    ]
