# Generated by Django 4.2 on 2023-06-19 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='error_test_case',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='error test case'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0caf9acd-2c17-4339-89a0-a9f53d5e4af8'), editable=False, verbose_name='uuid'),
        ),
    ]
