# Generated by Django 4.2 on 2023-06-19 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_attempt_error_test_case_alter_attempt_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('878a829d-29eb-4460-8040-4ff8eb98518d'), editable=False, verbose_name='uuid'),
        ),
    ]
