# Generated by Django 4.2 on 2023-06-19 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_attempt_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('273b3e1a-20ad-4038-aff5-1194ced6c846'), editable=False, verbose_name='uuid'),
        ),
    ]
