# Generated by Django 4.2 on 2023-06-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_attempt_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='uuid',
            field=models.UUIDField(editable=False, verbose_name='uuid'),
        ),
    ]
