# Generated by Django 4.2 on 2023-06-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_attempt_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('id',), 'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
    ]
