# Generated by Django 4.2 on 2023-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, verbose_name='uuid'),
        ),
    ]
