# Generated by Django 4.2 on 2023-06-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_attempt_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Attempt', 'verbose_name_plural': 'Attempts'},
        ),
    ]
