# Generated by Django 4.2 on 2023-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_alter_attempt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='error_test_case',
            field=models.PositiveIntegerField(default=0, verbose_name='error test case'),
        ),
    ]
